name: 'Deploy'
description: 'Deploy application'
inputs:
  app_version:
    description: 'Application version'
    required: true
runs:
  using: "composite"
  steps:

    - run: |
        cd app/deployment/k8s/spring-test
        helm upgrade --install spring-test ./ \
        --namespace spring-backstage-test --create-namespace \
        --set=image.repository=ghcr.io/sulimanns/spring-test \
        --set=service.port=8085 \
        --set=image.tag=${{ inputs.app_version}}
        
      shell: bash